export const DEFAULT_GRAPH = {
  nodes: [
    {
      id: "wake-early",
      title: "Wake up on time",
      notes: "Protect the first training hour.",
      startDate: "2026-03-17",
      bestBefore: "2026-03-18",
      expectedTime: 0.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "buy-shoes",
      title: "Buy running shoes",
      notes: "Visit the specialist store after work.",
      startDate: "2026-03-17",
      bestBefore: "2026-03-19",
      expectedTime: 1.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "choose-plan",
      title: "Choose marathon plan",
      notes: "Pick the 16-week plan and pin the checkpoints.",
      startDate: "2026-03-17",
      bestBefore: "2026-03-20",
      expectedTime: 1,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "mobility",
      title: "Glutes stretch",
      notes: "",
      startDate: "2026-03-17",
      bestBefore: "2026-03-17",
      expectedTime: 0.25,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "meal-prep",
      title: "Meal prep",
      notes: "Prepare recovery meals for the week.",
      startDate: "2026-03-18",
      bestBefore: "2026-03-18",
      expectedTime: 2,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "run-workout",
      title: "Running workout",
      notes: "Steady 8 km with cadence drill.",
      startDate: "2026-03-19",
      bestBefore: "2026-03-20",
      expectedTime: 1.25,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "strength",
      title: "Strength session",
      notes: "Posterior chain and core.",
      startDate: "2026-03-19",
      bestBefore: "2026-03-20",
      expectedTime: 1,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "long-run",
      title: "Long run",
      notes: "Progressive effort. Keep HR below threshold.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-23",
      expectedTime: 2.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "book-physio",
      title: "Book physio check-in",
      notes: "Short branch that still aligns on the outer shell.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-24",
      expectedTime: 0.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "log-splits",
      title: "Log workout splits",
      notes: "Capture pace, cadence, and recovery notes after the run.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-22",
      expectedTime: 0.25,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "stretch-calf",
      title: "Stretch calves",
      notes: "Post-run mobility that belongs to the same workout branch.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-22",
      expectedTime: 0.25,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "coach-review",
      title: "Coach review",
      notes: "Strength feedback checkpoint for the week.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-23",
      expectedTime: 0.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "recovery-review",
      title: "Recovery review",
      notes: "A multi-parent task that should visually merge workout and strength clusters.",
      startDate: "2026-03-22",
      bestBefore: "2026-03-23",
      expectedTime: 0.5,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
    {
      id: "marathon",
      title: "Marathon",
      notes: "Race day execution.",
      startDate: "2026-04-19",
      bestBefore: "2026-04-20",
      expectedTime: 4,
      realTime: 0,
      expectedEffort: null,
      realEffort: null,
      workStartedAt: null,
    },
  ],
  dependencies: [
    { parentId: "wake-early", childId: "run-workout" },
    { parentId: "buy-shoes", childId: "run-workout" },
    { parentId: "choose-plan", childId: "strength" },
    { parentId: "mobility", childId: "strength" },
    { parentId: "run-workout", childId: "long-run" },
    { parentId: "meal-prep", childId: "long-run" },
    { parentId: "run-workout", childId: "book-physio" },
    { parentId: "run-workout", childId: "log-splits" },
    { parentId: "run-workout", childId: "stretch-calf" },
    { parentId: "strength", childId: "coach-review" },
    { parentId: "run-workout", childId: "recovery-review" },
    { parentId: "strength", childId: "recovery-review" },
    { parentId: "long-run", childId: "marathon" },
    { parentId: "strength", childId: "marathon" },
  ],
  schedules: [
    { earlierId: "wake-early", laterId: "buy-shoes" },
    { earlierId: "buy-shoes", laterId: "choose-plan" },
    { earlierId: "run-workout", laterId: "strength" },
  ],
};
